SELECT
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_NAME`,
    `INFORMATION_SCHEMA`.`COLUMNS`.`COLUMN_NAME`,
    `INFORMATION_SCHEMA`.`COLUMNS`.`COLUMN_TYPE`,
    `INFORMATION_SCHEMA`.`COLUMNS`.`COLUMN_KEY`,
    `INFORMATION_SCHEMA`.`COLUMNS`.`IS_NULLABLE`,
    `INFORMATION_SCHEMA`.`COLUMNS`.`COLUMN_COMMENT`
FROM
    `INFORMATION_SCHEMA`.`TABLES`,
    `INFORMATION_SCHEMA`.`COLUMNS`
WHERE
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_SCHEMA` = "mmo_database"
AND
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_SCHEMA` =          `INFORMATION_SCHEMA`.`COLUMNS`.`TABLE_SCHEMA`
AND
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_NAME` = `INFORMATION_SCHEMA`.`COLUMNS`.`TABLE_NAME`
ORDER BY
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_NAME`, `INFORMATION_SCHEMA`.`COLUMNS`.`ORDINAL_POSITION`