SELECT
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_SCHEMA`,
    COUNT(*) AS number_of_tables
FROM
    `INFORMATION_SCHEMA`.`TABLES`
WHERE
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_SCHEMA` = "mmo_database"
GROUP BY
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_SCHEMA`