SELECT
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_NAME`,
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_TYPE`,
    `INFORMATION_SCHEMA`.`TABLES`.`DATA_LENGTH`,
    `INFORMATION_SCHEMA`.`TABLES`.`INDEX_LENGTH`,
    `INFORMATION_SCHEMA`.`TABLES`.`CREATE_TIME`,
    `INFORMATION_SCHEMA`.`TABLES`.`UPDATE_TIME`,
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_COLLATION`,
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_COMMENT`
FROM
    `INFORMATION_SCHEMA`.`TABLES`
WHERE
    `INFORMATION_SCHEMA`.`TABLES`.`TABLE_SCHEMA` = "mmo_database"
